apiVersion: v1
kind: PersistentVolume
metadata:
  name: dhtobb-hs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"